### ISSUE TITLE
Extension doesn't work anymore

### ISSUE THREAD

**Issue by AR15senalOfCode** [vokinpirks/Spicetify-SongTagger-Extension#2]
The extension does not create a tag menu anymore.

The BackendAPI's console window also doesn't say anything anymore, so Tagify doesn't even send any requests there.

**Comment by vokinpirks** [comment]
Hi, 
Sorry for a delay. Sadly, I have not been using this for quite a long time since Spotify doesn't work in my country anymore.
I installed Spotify through VPN to check whether the issue is relevant and if I could fix it.
Interestingly, the extension still works for me without any fixes. It applies and deletes tags as expected.
Be sure to update spicetify. Check if the exеension file is located in the spicetify extensions folder.

**Comment by AR15senalOfCode** [comment]
Thanks! Re-installing spicetify resolved the issue for me (deleting AppData\Local\spicetify and running the install script again).

I think there were other issues with my installation as well, it all works now though, thanks for the help!
